### ISSUE TITLE
Question about "didSelectNodeAt indexPath:"

### ISSUE THREAD

**Issue by saormart** [gringoireDM/LNZTreeView#5]
First, nice framework!
So, I'm trying to use the following function  to get the selected node to perform a segue:
`treeView(_ treeView: LNZTreeView, didSelectNodeAt indexPath: IndexPath, forParentNode parentNode: TreeNode?)`
but in the project it's not called if I add it to my viewController!
M'I doing something wrong ?
Thanks!

**Comment by batuhankok** [comment]
@saormart Hi!

```
extension MarksVC: LNZTreeViewDelegate {
    
    func treeView(_ treeView: LNZTreeView, didSelectNodeAt indexPath: IndexPath, forParentNode parentNode: TreeNodeProtocol?) {
        
    }
    
    func treeView(_ treeView: LNZTreeView, didExpandNodeAt indexPath: IndexPath, forParentNode parentNode: TreeNodeProtocol?) {
        
    }
    
    func treeView(_ treeView: LNZTreeView, didCollapseNodeAt indexPath: IndexPath, forParentNode parentNode: TreeNodeProtocol?) {
        
    }
    
}
```

**Comment by gringoireDM** [comment]
Hi @saormart this is an xCode issue I'm experiencing as well. And it's given by the fact that none of the three methods is optional, so when xCode checks for conformance to the protocol gives out on missing methods, but then it tries to understand if you actually implemented the missing method, but you spelled it. Since the methods are similar Xcode proposes a change. Writing all the three methods will solve the issue.

**Comment by saormart** [comment]
Thanks guys !
