### ISSUE TITLE
Out of range exception by dequeReusableCell by depthLevels >2 ?

### ISSUE THREAD

**Issue by gagoarm** [gringoireDM/LNZTreeView#6]
I have tested the demo version and Im having out of range exceptions on the cellForRowAt indexPath method.

When I open the levels and slide up/ down, by regenerating the cells I get the exception on the line where we are trying to get the specific node from the child's with the current index row.

- Is there any solution for this or is there any issue with the node identifiers? 
- Are the Node identifiers always (row_depth), even when the depthLevel is higher than 2?
- Im not using sections, should I use it for deeper levels maybe? How to use sections?

Thanks for sharing this code!

**Comment by gringoireDM** [comment]
Hi, I will investigate on this one. sorry for the delay.

**Comment by gringoireDM** [comment]
This issue was due to a very poor choice of the nodes identifier.

The implementation in ViewController ws using as identifier position_depthLevel which was causing duplicates. In a wise implementation of node this issue will not occur. make sure that your identifiers are unique for each node of the tree. Pushing now a fixed master.

Since this affects exclusively the demo and not the library there will not be a new pod version.

Sorry for taking so long.
